enabled_sites:
  - www.autotrader.co.uk
  - www.carandclassic.com
  - www.pistonheads.com
  - www.facebook.com
  - www.gumtree.com
redis:
  host: localhost
  port: 6379
  ttl: 300
  password: local # Use REDIS__PASSWORD env var
scraper:
  chrome_binary_location: /usr/bin/chromium
  disable_sandbox: True
  image_path: /tmp
